version: "3.7"

services:
  server:
    # Start with persistent name, to refer to kind network attachment
    container_name: registry.dreampop
    restart: always
    image: registry:2.7.1
    ports:
      - 127.0.0.1:5000:5000
    # environment:
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # REGISTRY_HTTP_ADDR: 0.0.0.0:443
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - data:/var/lib/registry
      # - ./certs:/certs
      # - ./auth:/auth

volumes:
  data: